@project.Presentation_HostAddress = http://localhost:5291

DELETE {{project.Presentation_HostAddress}}/my/
Accept: application/json
###

GET {{project.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

